-- -------------------------------------------------------------
	
    -- Resposta do Comando SQL item a)

INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'I');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'SAC', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS HUMANOS', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');


-- -------------------------------------------------------------
	
    -- Resposta do Comando SQL item b) 

/* inserindo dpto COMERCIAL  e seus funcionarios */ 
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-6, 1, 'Gabriela silva', 'GERENTE', 10230, TO_DATE('10102000','DDMMYYYY'), TO_DATE('13031960','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-6, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Tadeu ALves', 'ANALISTA', 5230, TO_DATE('18102000','DDMMYYYY'), TO_DATE('19031980','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-6, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Jorge Camargo', 'ANALISTA DE PROJ', 3430, TO_DATE('18102003','DDMMYYYY'), TO_DATE('19031982','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-6, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Eduarda Camargo', 'ANALISTA DE PROJ', 3450, TO_DATE('18101999','DDMMYYYY'), TO_DATE('20031982','DDMMYYYY'));

/* inserindo dpto CONTABILIDADE e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-5, 1, 'Joanete silva', 'GERENTE DE FINANÇAS', 12230, TO_DATE('10102003','DDMMYYYY'), TO_DATE('13031967','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-5, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Leticia Rochael', 'ANALISTA FINANCEIRO', 12980, TO_DATE('18072003','DDMMYYYY'), TO_DATE('19031988','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-5, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Leticio Soares', 'ANALISTA DE CONTAS', 5430, TO_DATE('18102003','DDMMYYYY'), TO_DATE('19031983','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-5, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Ana maria Camargo', 'ANALISTA DE PROJ', 3450, TO_DATE('18101999','DDMMYYYY'), TO_DATE('20031982','DDMMYYYY'));

/* inserindo dpto ESTOQUE e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-4, 1, 'Joane silva', 'GERENTE DE ESTOQUE', 8000, TO_DATE('10102001','DDMMYYYY'), TO_DATE('13031961','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-4, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Joana Dark', 'ESTOQUISTA', 3280, TO_DATE('21072001','DDMMYYYY'), TO_DATE('19031992','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-4, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Jose Soares', 'ESTOQUISTA', 2330, TO_DATE('18102003','DDMMYYYY'), TO_DATE('19031989','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-4, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Jonas Camargo junior', 'ESTOQUISTA 2', 6450, TO_DATE('18101994','DDMMYYYY'), TO_DATE('20031981','DDMMYYYY'));

/* inserindo dpto FINANCEIRO e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-3, 1, 'Jorginho Santos', 'GERENTE DE FINANCEIRO', 5000, TO_DATE('10101999','DDMMYYYY'), TO_DATE('13031971','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-3, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Marcos Palmas', 'FINANCEIRO', 2280, TO_DATE('21032001','DDMMYYYY'), TO_DATE('19031995','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-3, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Ronaldo smark', 'ESTAGIARIO', 2000, TO_DATE('18102000','DDMMYYYY'), TO_DATE('19031985','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-3, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Joao Jose Silva', 'ESTAGIARIO', 1450, TO_DATE('18101991','DDMMYYYY'), TO_DATE('20061981','DDMMYYYY'));

/* inserindo dpto SAC e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-2, 1, 'Marcia Santos', 'GERENTE DE SAC', 15000, TO_DATE('10101979','DDMMYYYY'), TO_DATE('13031981','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-2, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Gabriela Palmas', 'ATENDIMENTO', 2280, TO_DATE('21032001','DDMMYYYY'), TO_DATE('19031995','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-2, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Marques Moreno', 'ATENDIMENTO', 3400, TO_DATE('15102000','DDMMYYYY'), TO_DATE('19091985','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-2, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Joao Jose Soares', 'ESTAGIARIO', 2250, TO_DATE('18101990','DDMMYYYY'), TO_DATE('20061988','DDMMYYYY'));

/* inserindo dpto RECURSOS HUMANOS e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-1, 1, 'Gustavo Maraks', 'GERENTE DE RH', 13000, TO_DATE('10101978','DDMMYYYY'), TO_DATE('13031988','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-1, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Gabriel Silva', 'ANALISTA DE RH', 6280, TO_DATE('21032010','DDMMYYYY'), TO_DATE('19031999','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-1, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Jorge Moreno', 'ANALISTA DE RH', 7400, TO_DATE('15102001','DDMMYYYY'), TO_DATE('19091987','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL-1, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Marciana Jose', 'ESTAGIARIO', 2250, TO_DATE('18101991','DDMMYYYY'), TO_DATE('2006198','DDMMYYYY'));

/* inserindo dpto LOGISTICA e seus funcionarios */
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, 1, 'Ana Carolina Ryiu', 'GERENTE DE LOGISTICA', 12900, TO_DATE('10091978','DDMMYYYY'), TO_DATE('13031982','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Pablo vittar', 'ANALISTA DE LOGISTICA', 6280, TO_DATE('21032010','DDMMYYYY'), TO_DATE('19031999','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Jorge Italo', 'ENGENHEIRO DE LOGISTICA', 7400, TO_DATE('15102011','DDMMYYYY'), TO_DATE('19091981','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, SQ_MC_FUNCIONARIO.CURRVAL-3, 'Marcia Joari', 'ESTAGIARIO', 1250, TO_DATE('18101991','DDMMYYYY'), TO_DATE('2006198','DDMMYYYY'));


-- -------------------------------------------------------------
	
    -- Resposta do Comando SQL item c)

INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AC','ACRE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AL','ALAGOAS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AP','AMAPA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AM','AMAZONAS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('BA','BAHIA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('CE','CEARA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('DF','DISTRITO FEDERAL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('ES','ESPIRITO SANTO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('GO','GOIAS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MA','MARANHAO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MT','MATO GROSSO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MS','MATO GROSSO DO SUL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MG','MINAS GERAIS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PA','PARA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PB','PARAIBA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PR','PARANA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PE','PERNAMBUCO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PI','PIAUI');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RJ','RIO DE JANEIRO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RN','RIO GRANDE DO NORTE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RS','RIO GRANDE DO SUL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RO','RONDANIA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RR','RORAIMA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SC','SANTA CATARINA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SP','SAO PAULO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SE','SERGIPE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('TO','TOCANTINS');

/* populando parana */
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'PR','CURITIBA','',41);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'ALTO DA XV','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R JOSE DE ALENCAR',80040070);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R ALMIRANTE TAMANDAR?',80045110);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'AGUA VERDE','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV REPUBLICA ARGENTINA',80620970);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV DOS ESTADOS',80610040);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'PR','LONDRINA','',43);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'JARDIM PACAEMBU','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV SYLVIO BARROS',86079080);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV CURITIBA',86078100);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'PEROBINHA', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R GREOGRIO DE SOUZA VAC?RIO',86081558);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R LUIZ LEONI',86081631);

/* populando sao paulo */
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'SP','CAMPINAS','',19);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'GUANABARA','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R BARBOSA DE ANDRADE',13070158);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R DR BARROS MONTEIRO',13073240);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'TAQUARAL', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R BARBOSA DE ANDRADE',13070158);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R DR BARROS MONTEIRO',13073240);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'SP','SAO BERNARDO DO CAMPO','',11);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'ANCHIETA','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV KENNEDY',09726253);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV SENADOR VERGUEIRO',09600004);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'COOPERATIVA', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV S?O JORGE',09853705);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R ELISHA OTIS',09895400);
    
/* populando RIO DE JANEIRO */
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'RJ','NITEROI','',21);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'ITAIPU','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R TRES',24364122);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R OSMAR CORREIA DA SILVA',24342380);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'S?O FRANCISCO', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV QUINTINO BOCAIUVA',24360022);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R GUARARAPES',24360150);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'RJ','RIO DE JANEIRO','',21);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'SANTA TERESA','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R MONTE ALEGRE',20240193);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R GOMES LOPES',20241410);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'LAPA', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R DA LAPA',20021180);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R REALENGO',20231110);
    
/* populando SANTA CATARINA */
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'SC','CHAPECO','',49);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL,  SQ_MC_CIDADE.CURRVAL, 'BELA VISTA','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R CRISTOVAM COLOMBO',89804250);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R VIDAL RAMOS',89804360);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL,  SQ_MC_CIDADE.CURRVAL, 'ESPLANADA', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R BORGES DE MEDEIROS',89812454);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R AMAZONAS-E',89812452);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'SC','FLORIANOPOLIS','',48);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'CAMPECHE','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV CAMPECHE',88063301);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R DO GRAVATA',88063530);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'ESTREITO', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R DR HEITOR BLUM',88070300);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R QUATORZE DE JULHO',88075010);
/* populando ALAGOAS */
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'AL','MACEIO','', 82);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'CIDADE UNIVERSITARIA','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV TANCREDO NEVES',57073370);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV MENINO MARCELO',57000000);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'MANGABEIRAS', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'AV COMENDADOR GUSTAVO PAIVA',57032901);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'VER ANTONIO CAVALCANTE LINS',57037440);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL,'AL','ARAPIRACA','', 82);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'BANANEIRAS','');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R VICENTE MAGALHAES',57318450);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R JOAO FERREIRA BARBOSA',57317400);
    INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'OURO PRETO', '');
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R SAO FRANCISCO',57301110);
        INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R PROF DOMINGOS CORREIA',57301100);


-- -------------------------------------------------------------
	
    -- Resposta do Comando SQL item d)

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL,897656,'',TO_DATE('14062011','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-1, SQ_MC_LOGRADOURO.CURRVAL-1,833656,'',TO_DATE('14062012','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-2, SQ_MC_LOGRADOURO.CURRVAL-2,833256,'',TO_DATE('13062012','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-3, SQ_MC_LOGRADOURO.CURRVAL-3,8113656,'',TO_DATE('14072010','DDMMYYYY'),'','I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-4, SQ_MC_LOGRADOURO.CURRVAL-4,834556,'',TO_DATE('12052011','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-5, SQ_MC_LOGRADOURO.CURRVAL-5,832656,'',TO_DATE('14012009','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-6, SQ_MC_LOGRADOURO.CURRVAL-6,833656,'',TO_DATE('14062012','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-7, SQ_MC_LOGRADOURO.CURRVAL-7,833634,'',TO_DATE('14062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-8, SQ_MC_LOGRADOURO.CURRVAL-8,903634,'',TO_DATE('12062019','DDMMYYYY'),'','I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-9, SQ_MC_LOGRADOURO.CURRVAL-9,833900,'',TO_DATE('11062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-10, SQ_MC_LOGRADOURO.CURRVAL-11,098634,'',TO_DATE('09062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-11, SQ_MC_LOGRADOURO.CURRVAL-12,444634,'',TO_DATE('03062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-12, SQ_MC_LOGRADOURO.CURRVAL-12,000634,'',TO_DATE('03062014','DDMMYYYY'),'','I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-13, SQ_MC_LOGRADOURO.CURRVAL-13,830004,'',TO_DATE('07062014','DDMMYYYY'),'','I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-14, SQ_MC_LOGRADOURO.CURRVAL-14,345634,'',TO_DATE('07072020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-15, SQ_MC_LOGRADOURO.CURRVAL-15,0000023,'',TO_DATE('21112010','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-16, SQ_MC_LOGRADOURO.CURRVAL-16,443634,'',TO_DATE('14062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-17, SQ_MC_LOGRADOURO.CURRVAL-17,555634,'',TO_DATE('08092020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-18, SQ_MC_LOGRADOURO.CURRVAL-18,099634,'',TO_DATE('07062020','DDMMYYYY'),'','I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-19, SQ_MC_LOGRADOURO.CURRVAL-19,8333334,'',TO_DATE('09072017','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-20, SQ_MC_LOGRADOURO.CURRVAL-20,833999,'',TO_DATE('01072018','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-21, SQ_MC_LOGRADOURO.CURRVAL-21,837734,'',TO_DATE('09062020','DDMMYYYY'),'','A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_FUNCIONARIO.CURRVAL-22, SQ_MC_LOGRADOURO.CURRVAL-22,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');


-- -------------------------------------------------------------
	
    -- Resposta do Comando SQL item e)

/* cadastro 10 pessoas fisicas */
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'GABRIELA ALMEIDA', 'GABRIELAM', 'SENHA1111', 4, 1500.00, 'A', 'gabriela.almeida@example.com', '(11) 98765-4321');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('08/07/2016','DD/MM/YYYY'), 'F', '08502785689');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-16, 838884, '', TO_DATE('08/07/2016','DD/MM/YYYY'), '', 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'JOANA DA SILVA', 'JOANAS', 'SENHA1112', 3, 800.00, 'I', 'joana.silva@example.com', '(21) 99876-5432');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('02/07/2008','DD/MM/YYYY'), 'F', '08502285689');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-15, 838884, '', TO_DATE('08/07/2016','DD/MM/YYYY'), '', 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'MONICA DA ROSA','MONICAROSA','SENHA1113', 3, 125.99, 'A', 'monica.rosa@example.com', '(11) 98765-4321');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('08071992','DD-MM-YYYY'), 'F','08502785689');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-14,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'LETICIA LETRUX','LETICIALX','SENHA1114', 5, 319.99, 'I', 'leticia.letrux@example.com', '(11) 99876-5432');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('03072000','DD-MM-YYYY'), 'F','08502755559');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-15,838884,'',TO_DATE('08072016','DDMMYYYY'),'','I');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'ANA GABRIELA LETICIA','ANAGL','SENHA1115', 3, 200, 'A', 'ana.gabriela@example.com', '(11) 99999-9999');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('02072016','DD-MM-YYYY'), 'F','08502753339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-14,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'JOAO SILVA','JOAOSILVA','SENHA1116', 4, 350, 'A', 'joao.silva@example.com', '(11) 99999-8888');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('03072011','DD-MM-YYYY'), 'M','33302753339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-13,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'GABRIEL SANTOS','SANTOSG','SENHA1117', 3, 200.50, 'A', 'gabrielsantos@email.com', '(11) 99999-9999');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('02072016','DD-MM-YYYY'), 'M','08502753339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-12,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'MANOEL MATTOS','MANOELM','SENHA1118', 4, 500.00, 'A', 'manoelmattos@email.com', '(11) 88888-8888');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('10072016','DD-MM-YYYY'), 'M','1111753339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-11,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'MARCOS VIEIRA','MARCOSVI','SENHA1119', 4, 125.50, 'A', 'marcos.vieira@gmail.com', '+55 11 98888-8888');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('12072018','DD-MM-YYYY'), 'M','1444453339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-10,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'SAMUEL LIMA','LIMASAMUEL','SENHA1120', 3, 85.25, 'A', 'samuel.lima@gmail.com', '+55 11 97777-7777');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, NR_CPF)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('10102016','DD-MM-YYYY'), 'M','1111753339');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-9,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');


/* cadastro 5 CLIENTES JURIDICOS */
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'AÃ‡OUGUE LIMA','ACOUGUELIMA','SENHA1121', 4, 150.50, 'A', 'acouguelima@exemplo.com', '(11) 99999-9999');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO,NR_CNPJ, NR_INSCR_EST)
VALUES (SQ_MC_CLIENTE.CURRVAL,TO_DATE('12-04-1987','DD-MM-YYYY') ,'000000999888776', '192441339');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-8, 838884, '', TO_DATE('08072016','DDMMYYYY'), '', 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'SMERCADO ESTRELA LTDA','ESTRELAMERCADO','SENHA1122', 5, 350.25, 'A', 'estrelamercado@exemplo.com', '(11) 88888-8888');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO,NR_CNPJ, NR_INSCR_EST)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('12-02-1989','DD-MM-YYYY') ,'000000997658776', '192441332');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-7, 838884, '', TO_DATE('08072016','DDMMYYYY'), '', 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'FARMÃ�CIA CATARINENSE','CATARINENSEFARMACIA','SENHA1123', 4, 120.50, 'A', 'catarinensefarmacia@exemplo.com', '(47) 5555-5555');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO,NR_CNPJ, NR_INSCR_EST)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('18-02-1982','DD-MM-YYYY') ,'000000999798546', '192789523');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-6,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'MERCADO MAFFATO','MAFFATOMERCADO','SENHA1124', 3, 90.00, 'A', 'maffatomercado@exemplo.com', '(67) 5555-5555');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO,NR_CNPJ, NR_INSCR_EST)
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('13-09-1987','DD-MM-YYYY') ,'000000987562345', '197896753');
INSERT INTO MC_END_CLI (NR_CLIENTE,CD_LOGRADOURO_CLI , NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-5,838884,'',TO_DATE('08072016','DDMMYYYY'),'','A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, NM_LOGIN, DS_SENHA, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE) 
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'LOJA AMARAL', 'LOJAAMARAL', 'SENHA1125', 4, 500.00, 'A', 'lojaamaral@gmail.com', '(11) 98765-4321');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO,NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL,TO_DATE('12-07-1967','DD-MM-YYYY') ,'000000999895276', '197893652');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) 
VALUES (SQ_MC_CLIENTE.CURRVAL, SQ_MC_LOGRADOURO.CURRVAL-4, 838884, '', TO_DATE('08072016', 'DDMMYYYY'), '', 'A');


-- -------------------------------------------------------------

    -- Resposta do Comando SQL item f) 

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA)
VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Robson Hugo Silva', 3, 100.50, 'A', 'robinhood321@yahoo.com', '14 98799-9999', 'GABRIELAM', 'SENHA1111');

    /* 
        Nao foi possivel incluir o cliente, pois o campo login tem um constraint chamado 'UK_MC_CLIENTE_MM_LOGIN' que e unique.
        O erro retornado ao tentar rodar esta instrucao e a seguinte: ORA-00001: unique constraint (RM550259.UK_MC_CLIENTE_MM_LOGIN) violated 
    */


-- -------------------------------------------------------------

    -- Resposta do Comando SQL item g)

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Artesanato', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Audio', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Brinquedos', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Celular e Smartphone', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Colchoes', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Esporte e Lazer', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Ferramentas', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Games', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Informatica', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Livros', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Pet Shop', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'TV e Utilidades Domesticas', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');


-- -------------------------------------------------------------

    -- Resposta do Comando SQL item h)


-- Inserindo categorias na nova tabela
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Instalacao do produto', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Uso no cotidiano', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Comercial com personalidade', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Entre outros', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'A');


-- -------------------------------------------------------------

    -- Resposta do Comando SQL item i)

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '7896541236548', 'Smartphone XYZ', 1499.99, 'Caixa', 'A', 0.20, 'Smartphone XYZ com 128GB de armazenamento e 6GB de RAM');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 2, '7891234567891', 'Caixa de Som JBL', 499.00, 'Caixa', 'A', 40.00, 'Caixa de som portatil JBL Flip 5 com Bluetooth.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 3, '7891234567892', 'Carrinho de Controle Remoto', 129.99, 'Caixa', 'A', 50.00, 'Carrinho de controle remoto infantil.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '7891234567893', 'Smartphone Samsung Galaxy S21', 4999.00, 'Caixa', 'A', 30.00, 'Smartphone Samsung Galaxy S21 com camera tripla de 64 MP, 8K de gravacao, 256 GB de armazenamento e processador Exynos 2100.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 5, '7891234567894', 'Colchao Queen Ortobom', 1599.00, 'Caixa', 'A', 60.00, 'Colchao Queen size Ortobom de molas ensacadas e pillow top.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 6, '7891234567895', 'Bola de Futebol', 89.90, 'Caixa', 'A', 40.00, 'Bola de futebol tamanho oficial.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 3, '7891234567897', 'Bola de Futebol Nike', 89.99, 'Caixa', 'A', 0.50, 'Bola de Futebol Nike com design moderno e tecnologia que oferece maior durabilidade e precisao.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '7891234567903', 'Capa para Celular Samsung', 29.99, 'Caixa', 'A', 0.60, 'Capa para Celular Samsung resistente, com design moderno e facil de encaixar.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 5, '7891234567910', 'Colchao Ortobom', 999.99, 'Caixa', 'A', 0.40, 'Colchao Ortobom de alta qualidade e conforto, ideal para uma boa noite de sono.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 6, '7891234567927', 'Bicicleta Caloi', 1499.99, 'Caixa', 'A', 0.35, 'Bicicleta Caloi para uso urbano, com design moderno e resistente, ideal para quem busca uma alternativa de transporte sustentavel.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 7, '7891234567934', 'Furadeira Bosch', 279.99, 'Caixa', 'A', 0.55, 'Furadeira Bosch potente e resistente, ideal para uso profissional e domestico.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '7891234567941', 'Console Xbox Series X', 4999.99, 'Caixa', 'A', 0.30, 'Console Xbox Series X com tecnologia de ponta e alta capacidade de processamento, ideal para gamers exigentes.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '7894777756123', 'Headset Gamer', 199.90, 'Caixa', 'A', 40.0, 'Fone de ouvido para games com microfone');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '7895555456123', 'Teclado Mecanico', 349.90, 'Caixa', 'A', 40.0, 'Teclado mecanico para jogos com luz de led') ;
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '7894561554423', 'Monitor LED 24"', 899.90, 'Caixa', 'A', 30.0, 'Monitor LED de 24 polegadas para PC') ;
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '7894557556123', 'Notebook 14"', 2799.90, 'Caixa', 'A', 35.0, 'Notebook com processador i5 e memoria RAM de 8GB') ;
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 10, '789424747123', 'Livro - O Senhor dos Aneis', 49.90, 'Caixa', 'A', 20.0, 'Livro de fantasia Epica de J.R.R. Tolkien') ;
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 10, '789457786123', 'Livro - A Guerra dos Tronos', 59.90, 'Caixa', 'A', 25.0, 'Livro de fantasia Epica de George R. R. Martin') ;
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 11, '784859456123', 'Racao para Gatos', 29.90, 'Caixa', 'A', 35.0, 'Racao para gatos adultos sabor frango'); 
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 12, '789104034595', 'Racao para caes adultos sabor carne', 50.99, 'Caixa', 'A', 30.00, 'Racao para caes adultos de porte medio a grande, com sabor de carne e ingredientes selecionados para uma alimentacao saudavel e equilibrada.');


-- -------------------------------------------------------------

    -- Resposta do Comando SQL item j)

INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD)
VALUES (4, 1, 16, EMPTY_BLOB(), 'YT', 'https://www.youtube.com/watch?v=3nSzQjhbHe0', 'A');
INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD)
VALUES (14, 2, 16, EMPTY_BLOB(), 'VIMEO', 'https://vimeo.com/352516495', 'A');


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item k)

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (1, 1, 12, TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 10, 30, 45);
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (2, 2, 5, TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 11, 20, 15);
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (3, 3, 2, TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 14, 45, 30);
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (4, 4, 7, TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 16, 10, 55);
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (5, 5, 17, TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 18, 01, 10);

-- -------------------------------------------------------------

    -- Resposta do Comando SQL item l)

COMMIT;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item m)

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA)
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Automoveis', TO_DATE(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), NULL, 'I');


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item n)

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) 
VALUES (SQ_MC_PRODUTO.NEXTVAL, 10, '789444486120', 'Livro - Python para Data Science', 119.90, 'Caixa', 'I', 25.0, 'Livro de Primeiros passos na linguagem de John Paul Muller');


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item o)

UPDATE MC_FUNCIONARIO 
SET DS_CARGO = 'ESTOQUISTA 2', VL_SALARIO = VL_SALARIO * 1.12
WHERE CD_FUNCIONARIO = 33;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item p)

UPDATE MC_CATEGORIA_PROD
SET DS_CATEGORIA = 'Veiculos'
WHERE CD_CATEGORIA = 17;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item q)

UPDATE MC_DEPTO
SET NM_DEPTO = 'ESTOQUE1'
WHERE NM_DEPTO LIKE '%ESTOQUE%';


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item r)

UPDATE MC_CLI_FISICA
SET DT_NASCIMENTO = TO_DATE ('18-05-2002', 'DD-MM-YYYY')
WHERE NR_CLIENTE = 7;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item s)

UPDATE MC_CATEGORIA_PROD
SET DS_CATEGORIA = 'INFORMATIVO'
WHERE CD_CATEGORIA = 16;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item t)


UPDATE MC_FUNCIONARIO
SET ST_FUNC = 'I',
DT_DESLIGAMENTO = TO_DATE(SYSDATE)
WHERE CD_FUNCIONARIO = 33;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item u)
   
insert into MC_SGV_SAC (NR_SAC, NR_CLIENTE, CD_PRODUTO, 
                    CD_FUNCIONARIO, DS_DETALHADA_SAC, DT_ABERTURA_SAC ,HR_ABERTURA_SAC,
                    DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, NR_TEMPO_TOTAL_SAC, 
                    DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC, NR_INDICE_SATISFACAO)
values (SQ_MC_SGV_SAC.NEXTVAL, 7, 4, 40,
        'Recentemente, adquiri um produto da sua empresa e infelizmente, ao utiliza-lo, percebi que ele apresenta um problema. Acredito que possa ser um defeito de fabricacao, pois segui todas as instrucoes de uso indicadas na embalagem.',
        TO_DATE('09-04-2023 13:00:00', 'DD-MM-YYYY HH24:MI:SS'), 13, NULL, NULL,
        NULL ,
        null,
        'D', 'E', null);

update MC_SGV_SAC
SET DS_DETALHADA_RETORNO_SAC = 'Apos verificar as informacoes do seu chamado, verificamos que o seu problema foi solucionado com sucesso. O seu chamado foi atualizado com o status "FECHADO" e a data e hora de fechamento tambï¿½m foram registradas em nosso sistema. O tempo total de atendimento foi calculado e registrado em nossa base de dados.',
    DT_ATENDIMENTO = TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'),
    HR_ATENDIMENTO_SAC = TO_NUMBER(TO_CHAR(TO_DATE('14:00:00', 'HH24:MI:SS'), 'HH24')),
    NR_TEMPO_TOTAL_SAC = ROUND(TO_NUMBER(TO_CHAR(TO_DATE('00:01:30', 'HH24:MI:SS'), 'SSSSS'))),
    ST_SAC = 'F',
    NR_INDICE_SATISFACAO = 10
    where NR_SAC = 1;
    
insert into MC_SGV_SAC (NR_SAC, NR_CLIENTE, CD_PRODUTO, 
                    CD_FUNCIONARIO, DS_DETALHADA_SAC, DT_ABERTURA_SAC ,HR_ABERTURA_SAC,
                    DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, NR_TEMPO_TOTAL_SAC, 
                    DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC, NR_INDICE_SATISFACAO)
values (SQ_MC_SGV_SAC.NEXTVAL, 6, 3, 20,
        'Produto quebrado, favor reembolsar',
        TO_DATE('09-02-2023 14:00:00', 'DD-MM-YYYY HH24:MI:SS'), 13, NULL, NULL,
        NULL ,
        null,
        'D', 'A', null);
        
    
insert into MC_SGV_SAC (NR_SAC, NR_CLIENTE, CD_PRODUTO, 
                    CD_FUNCIONARIO, DS_DETALHADA_SAC, DT_ABERTURA_SAC ,HR_ABERTURA_SAC,
                    DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, NR_TEMPO_TOTAL_SAC, 
                    DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC, NR_INDICE_SATISFACAO)
values (SQ_MC_SGV_SAC.NEXTVAL, 1, 5, 16,
        'MTO BOM A LOJA E O PRODUTO',
        TO_DATE('09-02-2023 14:00:00', 'DD-MM-YYYY HH24:MI:SS'), 13, NULL, NULL,
        NULL ,
        null,
        'E', 'A', null);
-- -------------------------------------------------------------

	-- Resposta do Comando SQL item v)

UPDATE MC_END_CLI
SET ST_END = 'I', DT_TERMINO = TO_DATE(TO_CHAR(SYSDATE-1, 'YYYY-MM-DD'), 'YYYY-MM-DD')
WHERE NR_CLIENTE = 5;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item w)

UPDATE MC_END_FUNC
SET ST_END = 'I', DT_TERMINO = TO_DATE(TO_CHAR(SYSDATE-1, 'YYYY-MM-DD'), 'YYYY-MM-DD')
WHERE CD_FUNCIONARIO = 47 AND CD_LOGRADOURO = 36;


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item x) 
    
DELETE FROM MC_CIDADE
WHERE NM_CIDADE = 'CURITIBA';

    /*
        Nao e possivel deletar a cidade pois ainda ha referencias desta linha na tabela bairro, 
        pois o codigo da cidade e uma chave estrangeira na tabela bairro.
        Para que a cidade seja deletada com sucesso, e necessario que suas referencias em outras tabelas sejam apagadas. 
    */


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item y)

UPDATE MC_PRODUTO
SET ST_PRODUTO = 'X'
where cd_produto = 1;

    /*
        Nao se pode mudar o status para X pois ha um constraint do tipo check que checa constantemente se o status
        recebe A ou I. E deixa o campo ter apenas um desses dois valores.
    */


-- -------------------------------------------------------------

	-- Resposta do Comando SQL item z)
    
    CREATE TABLE mc_sgv_ocorrencia_sac (
    nr_ocorrencia_sac               NUMBER NOT NULL,
    dt_abertura_sac                 DATE,
    hr_abertura_sac                 NUMBER(2),
    ds_tipo_classificacao_sac       VARCHAR2(30) NOT NULL,
    ds_indice_satisfacao_atd_sac    VARCHAR2(30),
    cd_produto                      NUMBER(10),
    ds_produto                      VARCHAR2(80) NOT NULL,
    vl_unitario_produto             NUMBER(10,2) NOT NULL,
    vl_perc_lucro                   NUMBER(8,2),
    vl_unitario_lucro_produto       NUMBER(8,2),
    sg_estado                       CHAR(2) NOT NULL,
    nm_estado                       VARCHAR(2) NOT NULL,
    nr_cliente                      NUMBER(10) NOT NULL,
    nm_cliente                      VARCHAR2(160) NOT NULL,
    vl_icms_produto                 NUMBER(8,2)
);

ALTER TABLE mc_sgv_ocorrencia_sac ADD CONSTRAINT pk_mc_sgv_ocorrencia_sac PRIMARY KEY ( nr_ocorrencia_sac );
SELECT * FROM mc_sgv_sac    
COMMIT;


-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------